[tool.poetry]
name = "correct6x"
version = "1.0.1"
description = "Library to perform various corrections on native 6X imagery."
authors = []
include = [
    {path = "exiftool/*.exe", format = "wheel"}
]

[tool.poetry.dependencies]
python = "^3.7"
click = "*"
pandas = "*"
numpy = "*"
tqdm = "*"
opencv-contrib-python = "*"
imgparse = {git = "ssh://git@github.com/SenteraLLC/py-image-metadata-parser.git", tag = "v1.9.3"}

[tool.poetry.dev-dependencies]
pytest = "*"
sphinx_rtd_theme = "*"
sphinx = "*"
pre_commit = "*"

[tool.poetry.scripts]
correct6x = "correct6x.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
